---
title: "Quiz 1"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```
<style>
  body {
    text-align: justify}
</style>

### Question 1.

```{r q1}
question("The function ggplot() requires that the value supplied to the 'data' argument be a",
         answer("data.frame",correct = TRUE),answer("list"),answer("geom"),answer("character vector"))
```

### Question 2

</b>You run the following code and get the error printed directly after the code<b>

```{r q2a,eval = FALSE,echo = TRUE}
library(ggplot2)
library(faraway)
data(nepali)
head(nepali,3)
      id sex   wt   ht mage lit died alive age
1 120011   1 12.8 91.2   35   0    2     5  41
2 120011   1 12.8 93.9   35   0    2     5  45
3 120011   1 13.1 95.2   35   0    2     5  49
ggplot(nepali,aes(x = ht,y = wt))
    + geom_point()
Error in +geom_point(): invalid argument to unary operator
```


```{r q2b}
question("What happened?",
         answer("The nepali dataset lacks one or both of the two columns (ht,wt) that you used in the 
                aes statement of call."),
         answer("You have not yet loaded the nepali data frame."),
         answer("Because you put + at the start of the second line, instead of at the end of the first line, 
                R thought the call was over and tried to run the first line by itself, and then tried to run 
                the second line by itself, without an associated ggplot object.",correct = TRUE),
         answer("You are trying to create a scatterplot for a categorical variable.")
         )
```

### Question 3

```{r q3}
question("You have a dataset of observations on study subjects which has height and weight for each subject 
         measured at multiple time points. You want to create a scatterplot of height (x-axis) by weight (y-axis). 
         Since there are multiple measurements per subject, you would like to plot the measurements for each 
         subject in separate color. There is a column in the data called id that gives the unique id of each 
         study subject; this column currently has the class 'numeric'.</br></br> Which of the following 
         choices is a good strategy for creating a plot where data points use color to identify the subject?",
         answer("Convert the id column of the data frame to a factor, so a discrete palette will be used, 
                then use ggplot to create a scatterplot and specify color = id as the sole argument 
                in the geom_point() call.</br></br> Example code: </br>
                <pre>df %>% 
                mutate(id = factor(id)) %>% 
                ggplot(aes(x = height,y = weight)) + 
                geom_point(color = id)
                </pre>"),
         answer("Leave the id column of the data frame as a numeric, so a continuous color palette will be 
                used, then use ggplot2 to create a scatterplot and specify color = id in the aes() section 
                of the ggplot() call.</br></br>Example code:</br>
                <pre>df %>% 
                ggplot(aes(x = height,y = weight,color = id)) + 
                geom_point()
                </pre>"),
         answer("Leave the id column of the data frame as a numeric, so a continuous color palette will be used 
                ggplot to create a scetterplot, then use + to add the element color(aes(id)).</br></br>
                Example code: </br>
                <pre>df %>% 
                ggplot(aes(x = height,y = weight)) + 
                geom_point() + color(aes(id))
                </pre>"),
         answer("Convert the id column of the data frame to a factor, so a discrete color palatte will be used, then 
                ggplot2 to create a scatterplot and specify color = id in the aes() section of the ggplot() call.
                </br></br>Example code:
                <pre>df %>% 
                mutate(id = factor(id)) %>% 
                ggplot(aes(x = height,y = weight,color = id)) + 
                geom_point()
                </pre>",correct = TRUE))
```

### Question 4

```{r q4}
question("You want to save a figure from R as a pdf file named 'MyFig.pdf'. Which of the following describes 
         the proper steps to take?",
         answer("Wrap all your code to create the figure in a pdf statement.</br></br><pre>
                pdf('MyFig.pdf') { 
                ggplot(df,aes(x = x,y = y)) + geom_point()
                }
                </pre>"),
         answer("First run dev.on('MyFig.pdf') to open a pdf device, then run all your code to create the figure, 
                then use dev.off() to close the device.</br></br><pre>
                dev.on('MyFig.pdf')
                ggplot(df,aes(x = x,y = y)) + geom_point()
                dev.off()
                </pre>"),
         answer("First run pdf('MyFig.pdf') to open a pdf device, then run all your code to create the figure, 
                then use dev.off() to close the device.</br></br>Example code:<pre>
                pdf('MyFig.pdf')
                ggplot(df,aes(x = x,y = y)) + geom_point()
                dev.off()
                </pre>",correct = TRUE),
         answer("First run all your code to create the figure, then run pdf('MyFig.pdf') to open a pdf device, then 
                use pdf.off() to close the device.</br></br><pre>
                ggplot(df,aes(x = x,y = y)) + geom_point()
                pdf('MyFig.pdf')
                dev.off()
                </pre>"))
```

### Question 5.

<b>Consider the following dataset.</b>

```{r q5a,eval = FALSE,echo = TRUE}
library(lattice)
data(barley)
head(barley)
     yield   variety year            site
1 27.00000 Manchuria 1931 University Farm
2 48.86667 Manchuria 1931          Waseca
3 27.43334 Manchuria 1931          Morris
4 39.93333 Manchuria 1931       Crookston
5 32.96667 Manchuria 1931    Grand Rapids
6 28.96667 Manchuria 1931          Duluth
```

```{r q5b}
question("Which ggplot2 expression would make a scatterplot of year and yield while coloring each point 
         according to its variety?",
         answer("ggplot(data = barley,aes(year,yield,color = variety))"),
         answer("ggplot(data = barley,aes(year,yield)) + geom_point()"),
         answer("ggplot(data = barley,aes(year,yield)) + geom_point(color = variety)"),
         answer("ggplot(data = barley,aes(year,yield)) + geom_point(aes(color = variety))",correct = TRUE))
```

### Question 6.

<b>Consider the following dataset.</b>

```{r q6a,echo = TRUE,eval = FALSE}
data(trees)
head(trees)
  Girth Height Volume
1   8.3     70   10.3
2   8.6     65   10.3
3   8.8     63   10.2
4  10.5     72   16.4
5  10.7     81   18.8
6  10.8     83   19.7
```

```{r q6b}
question("You want to create a scatter plot showing Girth on the x-axis, Height on the y-axis, and 
         Volume with point size. Which of the following code would create that plot? Assume that we 
         have loaded ggplot2 and dplyr libraries!",
         answer("<pre>trees %>%
         ggplot(aes(x = Girth,y = Height)) + 
         geom_point(size = Volume)</pre>"),
         answer("<pre>trees %>% 
         ggplot() + 
         geom_point(x = Girth,y = Height,size = Volume)</pre>"),
         answer("<pre>trees %>% 
         ggplot(aes(x = Girth,y = Height,size = Volume)) + 
         geom_point()</pre>",correct = TRUE),
         answer("<pre>trees %>% 
         ggplot() + 
         geom_point(aes(x = Girth,y = Height,size = Volume))</pre>",correct = TRUE),
         answer("<pre>ggplot() + 
         geom_point(trees,
         aes(x = Girth,y = Height,size = Volume))</pre>"),
         answer("<pre>ggplot(trees,aes(x = Girth,y = Height,size = Volume)) + 
         geom_point()</pre>",correct = TRUE),
         answer("<pre>trees %>% 
         ggplot(aes(x = Girth,y = Height)) + 
         geom_point(aes(size = Volume))</pre>",correct = TRUE),
         answer("<pre>ggplot() + 
         geom_point(data = trees,
         aes(x = Girth,y = Height,size = Volume))</pre>",correct = TRUE)
)
```

### Question 7. 

```{r q7}
question("How can you create small multiples using ggplot2?",
         answer("Add a scales element to decrease the range of the plot sclales."),
         answer("Add facet_grid to the geom, specifying one or two columns to use for faceting.",correct = TRUE),
         answer("Add multiple geoms to the plot using the + syntax."),
         answer("Add facet_wrap to the geom, specyfying the formula to use for faceting",correct = TRUE))
```

### Question 8.

```{r q8}
question("What does geom_smooth(method = 'lm') do when it is added to a ggplot object?",
         answer("It adds a fitted linear regression line to the plot",correct = TRUE),
         answer("It adds a nonlinear smoother to the plot."),
         answer("It adds transparency to the points to avoid over plotting."),
         answer("It adds a paletter of colors for plotting the points in a scatterplot."))
```

### Question 9.

```{r q9}
question("When plotting multiple panels using faceting for a single variable, what controls the order in which the 
         panels are plotted?",
         answer("Panels are ordered randomly."),
         answer("The order of panels must be specified by the user."),
         answer("Panels are ordered by the alphabetical order or by the order of the levels of the 
                faceting variable",correct = TRUE),
         answer("Panels are ordered by the bumber of data points in each panel"))
```

### Question 10.

```{r q10}
question("What function would you use to limit the range of the x-axis in a scatterplot?",
         answer("scale_x_continuous()",correct = TRUE),
         answer("scale()"),
         answer("geom_scale()"),
         answer("scale_y_continuous()"))
```